#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides:          shadowsocks-libev
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Fast tunnel proxy that helps you bypass firewalls
# Description:       Start or Stop the shadowsocks-libev server to support multiple users with ss-manager
### END INIT INFO

# Author: QuNiu <https://github.com/quniu>

if [ -f /usr/local/bin/ss-server ]; then
    DAEMON=/usr/local/bin/ss-server
elif [ -f /usr/bin/ss-server ]; then
    DAEMON=/usr/bin/ss-server
fi
NAME=shadowsocks-manager
CONF=/etc/shadowsocks-manager/config.json
SS_NAME=shadowsocks-manager-node
PID_DIR=/var/run
PID_FILE=$PID_DIR/shadowsocks-manager.pid
RET_VAL=0

[ -x $DAEMON ] || exit 0

if [ ! -d $PID_DIR ]; then
    mkdir -p $PID_DIR
    if [ $? -ne 0 ]; then
        echo "Creating PID directory $PID_DIR failed"
        exit 1
    fi
fi

if [ ! -f $CONF ]; then
    echo "$NAME config file $CONF not found"
     exit 1
fi

check_running() {
    if [ -r $PID_FILE ]; then
        read PID < $PID_FILE
        if [ -d "/proc/$PID" ]; then
            return 0
        else
            rm -f $PID_FILE
            return 1
        fi
    else
        return 2
    fi
}

check_manager_running(){
    SS_PID=$(ps -ef | grep -v grep | grep -i "${SS_NAME}" | awk '{print $2}')
    if [ -n "$SS_PID" ]; then
        return 0
    else
        return 1
    fi
}

do_status() {
    check_running
    case $? in
        0)
        echo "$NAME (pid $PID) is running..."
        ;;
        1|2)
        echo "$NAME is stopped"
        RET_VAL=1
        ;;
    esac
}

do_start() {
    if check_running; then
        echo "$NAME (pid $PID) is already running..."
        exit 0
    else
        $DAEMON -v -c $CONF -f $PID_FILE
        if check_running; then
            echo "Starting $NAME success"
        else
            echo "Starting $NAME failed"
            RET_VAL=1
        fi

        if [ $RET_VAL -eq 0 ]; then
            screen -dmS $SS_NAME ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:6001
            check_manager_running
            if [ $? -eq 0 ]; then
                echo "Starting $SS_NAME (PID $SS_PID) success"
            else
                echo "Starting $SS_NAME failed"
                RET_VAL=1
            fi
        fi  
    fi
}

do_stop() {
    if check_running; then
        kill -9 $PID
        rm -f $PID_FILE
        echo "Stopping $NAME success"

        if [ $RET_VAL -eq 0 ]; then
            check_manager_running
            if [ $? -eq 0 ]; then
                kill -9 $SS_PID
                screen -wipe > /dev/null 2>&1
                check_manager_running
                if [ $? -eq 1 ]; then
                    echo "Stopping $SS_NAME success"
                else
                    echo "Stopping $SS_NAME failed"
                    RET_VAL=1
                fi
            else
                echo "Stopping $SS_NAME failed"
                RET_VAL=1
            fi
        fi
    else
        echo "$NAME is stopped"
        RET_VAL=1
    fi
}

do_restart() {
    do_stop
    sleep 0.5
    do_start
}

case "$1" in
    start|stop|restart|status)
    do_$1
    ;;
    *)
    echo "Usage: $0 { start | stop | restart | status }"
    RET_VAL=1
    ;;
esac

exit $RET_VAL
